### ISSUE TITLE
Sad, doesnt work

### ISSUE THREAD

**Issue by kangarooo** [RomanistHere/YouTube-Search-Playlist#3]
Sad, doesnt work
![image](https://user-images.githubusercontent.com/73187/206879346-6e950b00-10b0-4efe-9c9a-1ff419ac9671.png)

**Comment by RomanistHere** [comment]
youtube changed it's policy like 20 times since the last time it worked, including making "liked" videos private only playlist, sad

extension is out of support for years now, sorry it confused you

**Comment by kangarooo** [comment]
This is my own public playlist. Its not liked videos.
Can update readme file for what it works now? #4
